<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <p><a id="logo" href="http://scala-lang.org/"><img src="/sites/default/files/icons/Scala_Logo2008.png" alt="scala-lang.org" border=0/></a></p>
    <title id="Title">Aladdin - Scala Bugtracking</title>
        <style type="text/css">
        table {
            font-size: 10pt;
            background-color: #ebb85c;
        }
        tr.impair        { background-color: #f0be64 }
        tr.impairContrib { background-color: #f0be64 }

#buraq-content {
	float: none;
	color: black;
	background-color: white;
	font-size: 1.25em;
	margin-left: 9.6em;
}
        </style>
      </head>
  <body><!--DisplayBugsBlock_Start-->




<table WIDTH="100%" cellspacing="4" cellpadding="2">

	<tr><td></td>
		<th>[#484]</th>
		<th><strong>project:</strong> nsc</th>
		<th><strong>priority:</strong> low</th>
		<th><strong>category:</strong> bug</th>
        </tr>

        <tr>
          <td></td>
	  <th align="center">submitter</th>
	  <th align="center">assigned to</th>
	  <th align="center">status</th>
	  <th align="center">date submitted</th>
        </tr>

        <tr>
          <td></td>
	  <td align="center" bgcolor="#FFFFFF">Iulian</td>
	  <td align="center" bgcolor="#FFFFFF">Iulian</td>
	  <td align="center" bgcolor="#FFFFFF">fixed</td>
          <td align="center" bgcolor="#FFFFFF">2005-11-10 16:56:15.0</td>

	</tr>

        <tr>
		<th align="right">subject</th>
		<td colspan="4" bgcolor="#FFFFFF">try catch blocks inside expressions generate invalid code</td>
	</tr>
	<tr>	
		<th align="right">code</th>
		<td colspan="4" bgcolor="#FFFFFF">
	<font size="-1"><pre>object Foo extends AnyRef with Application {
  val x = 1;

  Console.print(&quot;1 + 1 = &quot;);
  Console.println(1 + (try {
    x;
  } catch {
    case _: Error =&gt; 5;
  }))
}</pre></font></td>
	</tr>
	<tr>
		<th style="text-align:right;">what happened</th>
		<td colspan="4" style="background-color:#FFFFFF;" ><pre>Bytecode will fail verification. The reason is the way JVM handles the stack when exceptions occur: it clears th\
e stack, pushes the exception object and transfers control to the appropriate handler. This way, all intermediat\
e values found on the operand stack are lost (in our example, it is the Console.MODULE$ instance and the first '\
1' in the addition). When the exception handler transfers control back to the instructions after the try-catch b\
lock, the stack will contain only the result value in the exception handler (here, 5), while normal control flow\
 will contain the object and the int.
</pre></td>
	</tr>
	<tr>
		<th align="right">what expected</th>
		<td colspan="4" bgcolor="#FFFFFF" >Correct compilation. This can be solved either through a transformation on source code to 'lift' try-catch blocks outside contexts that depend on previous results (Apply nodes or Assignment to fields, etc.), or through stack dumping: before entering a Try block, all operands on the stack are saved to local variables, and each exception handler restores the stack before handling the exception.</td>
	</tr>
	<tr>
	
  <td colspan="4" align="right">
      
      <a href="displayBugs.do.html">
        [back to overview]</a></td></tr>

</table>

  <tr>
          <td align="center" colspan="2">
            <strong>Changes of this bug report</strong>
          </td>
        </tr><table><tr>
        <td>
        <strong>Iulian&nbsp; edited on &nbsp;2005-11-10 16:57:26.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>

</td></tr>
<tr>
        <td>
        <strong>Iulian&nbsp; edited on &nbsp;2005-11-16 17:41:45.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>

</td></tr></table>
<!--DisplayBugsBlock_End-->  </body>
</html>