<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <p><a id="logo" href="http://scala-lang.org/"><img src="/sites/default/files/icons/Scala_Logo2008.png" alt="scala-lang.org" border=0/></a></p>
    <title id="Title">Aladdin - Scala Bugtracking</title>
        <style type="text/css">
        table {
            font-size: 10pt;
            background-color: #ebb85c;
        }
        tr.impair        { background-color: #f0be64 }
        tr.impairContrib { background-color: #f0be64 }

#buraq-content {
	float: none;
	color: black;
	background-color: white;
	font-size: 1.25em;
	margin-left: 9.6em;
}
        </style>
      </head>
  <body><!--DisplayBugsBlock_Start-->




<table WIDTH="100%" cellspacing="4" cellpadding="2">

	<tr><td></td>
		<th>[#575]</th>
		<th><strong>project:</strong> compiler</th>
		<th><strong>priority:</strong> low</th>
		<th><strong>category:</strong> bug</th>
        </tr>

        <tr>
          <td></td>
	  <th align="center">submitter</th>
	  <th align="center">assigned to</th>
	  <th align="center">status</th>
	  <th align="center">date submitted</th>
        </tr>

        <tr>
          <td></td>
	  <td align="center" bgcolor="#FFFFFF">Sean</td>
	  <td align="center" bgcolor="#FFFFFF">Nikolay</td>
	  <td align="center" bgcolor="#FFFFFF">fixed</td>
          <td align="center" bgcolor="#FFFFFF">2006-04-25 16:04:15.0</td>

	</tr>

        <tr>
		<th align="right">subject</th>
		<td colspan="4" bgcolor="#FFFFFF">Checked exceptions broken when calling Scala from Java</td>
	</tr>
	<tr>	
		<th align="right">code</th>
		<td colspan="4" bgcolor="#FFFFFF">
	<font size="-1"><pre>example java code:


try {
  file.read();
} catch (IOException e) {
  ...
}</pre></font></td>
	</tr>
	<tr>
		<th style="text-align:right;">what happened</th>
		<td colspan="4" style="background-color:#FFFFFF;" ><pre>"read()" is implemented in Scala.

Above code does not compile because checked exceptions can only be caught if they are specified to be thrown. Be\
cause Scala does not generate throw information, checked exceptions can never be caught when calling Scala metho\
ds (have to catch Throwable).
</pre></td>
	</tr>
	<tr>
		<th align="right">what expected</th>
		<td colspan="4" bgcolor="#FFFFFF" >Not sure. This is a hard issue to fix. I guess calling Scala from Java is just a very tricky thing to do. Better to not mix the languages as much as possible (try not to call Scala libraries from Java).</td>
	</tr>
	<tr>
	
  <td colspan="4" align="right">
      
      <a href="displayBugs.do.html">
        [back to overview]</a></td></tr>

</table>

  <tr>
          <td align="center" colspan="2">
            <strong>Changes of this bug report</strong>
          </td>
        </tr><table><tr>
        <td>
        <strong>Martin&nbsp; edited on &nbsp;2006-04-26 11:37:53.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>
As Nik suggests, I think this is a case for attributes.
something like

  [throws[java.io.IOException]]
  def read() = ...

where `throws' is an attribute class, defined as follows:

  class throws[T <: Throwable] extends Attribute

We should define this attribute and translate it into a throws clause. If there are several exceptions thrown, we can express this by several `throws' attributes, i.e.

[throws[A], throws[B]] def foo() = ...

Nik, do you want to do this (maybe with the help of Iulian)?


</td></tr>
<tr>
        <td>
        <strong>Nikolay&nbsp; edited on &nbsp;2006-05-19 17:03:42.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>
Added an attribute - scala.throws(exc: Class) - to specify the exceptions thrown by a method:
<code>
[throws(classOf[java.io.IOException]),
 throws(classOf[java.io.FileNotFoundException])]
def read() = ...
</code>
</td></tr></table>
<!--DisplayBugsBlock_End-->  </body>
</html>